### ISSUE TITLE
Every seconds strange error

### ISSUE THREAD

**Issue by imc67** [sanjoyg/dirigera_platform#142]
Every x seconds ....:

Logger: custom_components.dirigera_platform
Bron: custom_components/dirigera_platform/hub_event_listener.py:303
integratie: IKEA Dirigera Hub Integration ([documentatie](https://github.com/sanjoyg/dirigera_platform), [problemen](https://github.com/sanjoyg/dirigera_platform))
Eerst voorgekomen: 10:30:10 (32 gebeurtenissen)
Laatst gelogd: 10:34:46

{"id":"dbb58f00-0b66-4d6d-ba01-a5b369b93451","time":"2025-03-08T09:34:38.430Z","specversion":"3.164.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"67653de3-a115-42d2-af70-32933850a304_1","type":"sensor","deviceType":"environmentSensor","createdAt":"2024-03-10T14:12:42.000Z","isReachable":true,"lastSeen":"2025-03-08T09:34:38.000Z","attributes":{"currentRH":68},"remoteLinks":[]}}
{"id":"03f666f4-a8a6-41ba-bcc6-988737fb2649","time":"2025-03-08T09:34:39.448Z","specversion":"3.164.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"67653de3-a115-42d2-af70-32933850a304_1","type":"sensor","deviceType":"environmentSensor","createdAt":"2024-03-10T14:12:42.000Z","isReachable":true,"lastSeen":"2025-03-08T09:34:39.000Z","attributes":{"currentRH":69},"remoteLinks":[]}}
{"id":"738f8ee0-c830-4e9b-9c8e-8ac909c88b64","time":"2025-03-08T09:34:40.471Z","specversion":"3.164.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"67653de3-a115-42d2-af70-32933850a304_1","type":"sensor","deviceType":"environmentSensor","createdAt":"2024-03-10T14:12:42.000Z","isReachable":true,"lastSeen":"2025-03-08T09:34:40.000Z","attributes":{"currentRH":68},"remoteLinks":[]}}
{"id":"179119cd-ab20-49d9-aae3-507858337e74","time":"2025-03-08T09:34:45.571Z","specversion":"3.164.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"67653de3-a115-42d2-af70-32933850a304_1","type":"sensor","deviceType":"environmentSensor","createdAt":"2024-03-10T14:12:42.000Z","isReachable":true,"lastSeen":"2025-03-08T09:34:45.000Z","attributes":{"currentRH":69},"remoteLinks":[]}}
{"id":"6816d20c-437c-4594-853d-570d0bc8b61d","time":"2025-03-08T09:34:46.591Z","specversion":"3.164.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"67653de3-a115-42d2-af70-32933850a304_1","type":"sensor","deviceType":"environmentSensor","createdAt":"2024-03-10T14:12:42.000Z","isReachable":true,"lastSeen":"2025-03-08T09:34:46.000Z","attributes":{"currentRH":68},"remoteLinks":[]}}

**Comment by sanjoyg** [comment]
What is the issue?

**Comment by Vetti52** [comment]
These three messages occur (copied from the homeassistant log file):
```
2025-03-08 15:44:01.156 ERROR (Thread-2) [custom_components.dirigera_platform] 'NoneType' object has no attribute 'loop'
2025-03-08 15:44:05.255 ERROR (Thread-2) [custom_components.dirigera_platform] error processing hub event
2025-03-08 15:44:05.255 ERROR (Thread-2) [custom_components.dirigera_platform] {"id":"7d719f94-019b-4286-8b39-cd4356713f6e","time":"2025-03-08T14:44:05.223Z","specversion":"3.164.0","source":"urn
:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"9fea4ac9-cc45-425e-910e-bb1f5fea9424_1","type":"outlet","deviceType":"outlet","createdAt":"2025-03-02T13:42:20.000Z","is
Reachable":true,"lastSeen":"2025-03-08T14:44:05.000Z","attributes":{"currentVoltage":239.89999389648438},"remoteLinks":[]}}
```
They are created from hub_event_listener.py line 300 to line 304
```
        except Exception as ex:
            logger.error("error processing hub event")
            logger.error(f"{ws_msg}")
            logger.error(ex)

```

I just helped myself by replacing logger.error with logger.debug. So the thousands of messages are „silenced“ now. What else do you need for further narrowing down the issue?

**Comment by sanjoyg** [comment]
Try the latest release, should be fixed

**Comment by Vetti52** [comment]
This was after Installation of the latest release. These errors still
exist. They have a different origin, as i mentioned. I think, it is due to
the very special measuring data, which the Inspelning plug produces.

Sanjoy Ghosh ***@***.***> schrieb am So., 9. März 2025, 07:01:
